version: '3.2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfiles/ecs/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./dashboard_api
        target: /app/dashboard_api
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - MODULE_NAME=dashboard_api.main
      - MEMCACHE_HOST=memcached
      - MEMCACHE_USERNAME=myuser
      - MEMCACHE_PASSWORD=mypassword
      - DATASET_METADATA_FILENAME=${STAGE}-dataset-metadata.json
      - PORT=8000
      - PYTHONWARNINGS=ignore
      - VARIABLE_NAME=app
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      - WORKERS_PER_CORE=5

  memcached:
    image: remotepixel/memcached-sasl:latest
    environment:
      - MEMCACHED_USERNAME=myuser
      - MEMCACHED_PASSWORD=mypassword
    ports:
      - "11211:11211"

  dashboard:
    build:
      context: https://github.com/nasa-impact/covid-dashboard.git#abarciauskas-bgse_sample-app
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
